# Generated by Django 3.0.6 on 2020-06-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='post',
            field=models.TextField(default='post updated soon'),
        ),
    ]
