# Generated by Django 3.0.6 on 2020-06-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_faculty_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstyear',
            name='branch',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='fourthyear',
            name='branch',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='secondyear',
            name='branch',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='thirdyear',
            name='branch',
            field=models.TextField(default='NA'),
        ),
    ]
