# Generated by Django 3.0.6 on 2020-06-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200619_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('year', models.TextField()),
                ('branch', models.TextField(default='NA')),
            ],
        ),
    ]
